administration-menus/index.md
credits/index.md
developer-tools/index.md
index.md
intro/index.md
intro/what-is-a-plugin/index.md
javascript/index.md
metadata/index.md
plugin-basics/index.md
post-types/index.md
security/index.md
settings/index.md
taxonomies/index.md

旧日本語版リポジトリ（[plugin-handbook](https://github.com/jawordpressorg/plugin-handbook)）で翻訳済のページを、当リポジトリに反映します。

旧リポジトリで翻訳済のページを反映

---

README.md

日本語翻訳作業に関するドキュメントを、既存のREDMEファイルを利用して作成しました。コンテンツの内容は、[ブロックエディターハンドブック翻訳ファイル管理リポジトリ](https://github.com/jawordpressorg/gutenberg)と全く同じです。

日本語版READMEコンテンツの作成

---

developer-tools/helper-plugins/index.md

原文との同期（[8772281](https://github.com/jawordpressorg/developer-plugins-handbook/commit/8772281ff2275e15b670244f9f01e4c98d82feb0) ）によって発生した追加テキストを翻訳しました。
二文だけのため、このままマージします。

翻訳: developer-tools/helper-plugins/index.md

---

README.md

アップストリームブランチと同期するときのコマンドですが、アップストリームのメインブランチは `trunk` ではなく `main` なので、修正しました。

Docs: リポジトリの管理方法のタイポを修正

---

users/working-with-user-metadata/index.md

4dd6fc2 で原文と同期したときに、誤って原文の重複が一か所でてしまったため、修正。

users/working-with-user-metadata/index.md: 原文の重複を削除

---

wordpress-org/transferring-your-plugin-to-a-new-owner/index.md

※36行目：「スクロールダウンします」に対して、「スク権限グループダウン」に修正せよ、と。
※56行目：「防止する為」に対して、「ため」に修正せよ、と。
※75行目：「殆どのリクエスト」「確実に繋がっている」に対して、それぞれ「ほとんど」「つながっている」に修正せよ、と。
そこからブランチ

fixes #204 wordpress-org/transferring-your-plugin-to-a-new-owner/index.md 和訳しました。

---

wordpress-org/special-user-roles-capabilities/index.md

※9行目：「保護する為に」に対して、「ため」に修正せよ、と。
※14行目：「ユーザーが持てる」に対して、「持ている」に修正せよ、と。
※34行目：「スクロールダウンし」に対して、「スク権限グループダウン」に修正せよ、と。
※49行目：「所有権を譲渡する為に」に対して、「ため」に修正せよ、と。
そこからブランチ

fixes #206 wordpress-org/special-user-roles-capabilities/index.md 和訳しました。

---

wordpress-org/release-confirmation-emails/index.md

fixes #208 wordpress-org/release-confirmation-emails/index.md 和訳しました。

---

wordpress-org/add-your-plugin-to-the-block-directory/index.md

※36行目：「インストールする為に」「遥かに小さく」に対して、それぞれ「ため」「はるか」に修正よ、と。
※75行目：「この様なプラグイン」に対して、「このような」に修正よ、と。
そこからブランチ

fixes #212 wordpress-org/add-your-plugin-to-the-block-directory/index.md 和訳しました。

---

wordpress-org/preventing-wordpress-from-updating-your-external-plugin/index.md

下記の和訳について。削除する必要があるのは、「以下の手順に含まれている事項」ですかね？
※退避原文12行目：Any plugin hosted here that is found to include this plugin will be closed and the developer required to remove it in order for their plugin to be restored.
※本文14行目：ここでホストされているプラグインで、この手順が含まれていることが判明すると、プラグインはクローズされ、開発者は自分のプラグインを復活させる為に、この手順を削除する必要があります。
※29行目：「の様なフォルダー名」「例えば」に対して、それぞれ「のような」「たとえば」に修正せよ、と。
※34行目：「を使用している為」に対して、「ため」に修正せよ、と。
※49行目：「例えば」に対して、「たとえば」に修正せよ、と。
そこからブランチ

fixes #214 wordpress-org/preventing-wordpress-from-updating-your-external-plugin/index.md 和訳しました。

---

wordpress-org/plugin-security/reporting-plugin-security-issues/index.md

※14行目：「殆どありません」に対して、「ほとんど」に修正せよ、と。
※40行目：「殆どのプラグイン」に対して、「ほとんど」に修正せよ、と。
※40行目：「共通脆弱性識別子データベース」に対して、「漢字が6文字以上連続している」、と。
※45行目：「既に脆弱性を公開で投稿」に対して、「すでに」に修正せよ、と。
そこからブランチ

fixes #210 wordpress-org/plugin-security/reporting-plugin-security-issues/index.md 和訳しました。

---

administration-menus/sub-menus/index.md

　34行目：例え => たとえ
　39行目：行ない => 行い
　44行目：お勧め => おすすめ
　74行目：行なう => 行う
　103行目：組み込みの => 組込み
　137行目：5 以 => 5以
　149行目：全く => まったく
　159行目：全く => まったく

fixes #220 administration-menus/sub-menus/index.md textlint再実施

---

internationalization/localization/index.md

　14行目：に 1 => に1
　14行目：0 文 => 0文
　39行目：1 つ => 1つ
　39行目：き 1 => き1
　59行目：することができ => でき
　59行目：及び =>  および
　59行目：することができ => でき
　83行目：で使用することもでき => でも使用でき
　83行目：することができ => でき
　83行目：することができ => でき
　83行目：することができ => でき
　93行目：grunt => Grunt
　93行目：grunt => Grunt
　103行目：例え => たとえ
　103行目：なので、 => ですので、
　103行目：及び =>  および
　118行目：エディタ => エディター
　118行目：することができ => でき
　118行目：エディタ => エディター
　118行目：の様に => のように
　129行目：の様に => のように
　142行目：を使用することもでき => も使用でき
　152行目：第 3 => 第3
　152行目：することができ => でき
　152行目：行なわ => 行わ
　157行目：ご紹介 => 紹介
　178行目：の様な => のような
　183行目：Unix => UNIX
　201行目：することができ => でき
　201行目：例え => たとえ
　206行目：Unix => UNIX
　226行目：の様に => のように
　278行目：る筈 => るはず
　298行目：、  => 、
　298行目：の様な => のような
　308行目：の様な => のような
　308行目：の様に => のように
　308行目：勿論 => もちろん
　318行目：7 以 => 7以
　323行目：行なっ => 行っ
　333行目：例え => たとえ

fixes #244 internationalization/localization/index.md textlint再実施

---

javascript/jquery/index.md

　70行目：までで => まで　←誤判定　「迄」は漢字にした方が良い場合もあるのでは？
　14行目：は 2 => は2
　14行目：セレクター => セレクタ
　23行目：セレクター => セレクタ
　23行目：時 => 際
　28行目：基づ => もとづ
　60行目：出力することができ => 出力でき
　60行目：なので、 => ですので、
　60行目：出力することができ => 出力でき
　65行目：セレクター => セレクタ
　70行目：セレクター => セレクタ
　70行目：セレクター => セレクタ
　70行目：の 2 => の2

fixes #254 javascript/jquery/index.md textlint再実施

---

javascript/heartbeat-api/index.md

　9行目：行なう => 行う
　14行目：仕組み => しくみ
　19目：5 ～ => 5～
　19目：0 秒 => 0秒
　19目：ハンドラー => ハンドラ
　38目：ち 1 => ち1
　38目：は 2 => は2
　38目：使用することもできます => 使用できます
　48目：2 つ => 2つ
　122目：ら 3 => ら3
　122目：訳 => わけ
　122目：例え => たとえ
　122目：の 2 => の2
　122目：使用することができ => 使用でき

fixes #252 javascript/heartbeat-api/index.md textlint再実施

---

javascript/ajax/index.md

　21行目：エントリー => エントリ　←警告が永久ループ（対処したら、今度は元に戻せ、とエラーが出る）になるので、textlintルールセットの見直しを提案します。
　238行目：t( => t (　←誤判定
　16行目：事 => こと
　74行目：ブラウザー => ブラウザ

fixes #248 javascript/ajax/index.md textlint再実施

---

internationalization/security/index.md

　30行目：を追加することも可能です => も追加可能です
　108行目：方 => ほう

fixes #246 internationalization/security/index.md textlint再実施

---

metadata/managing-post-metadata/index.md

Fixes #260
　49行目：エントリー => エントリ　←警告が永久ループ（対処したら、今度は元に戻せ、とエラーが出る）
　49行目：エントリー => エントリ　←警告が永久ループ（対処したら、今度は元に戻せ、とエラーが出る）
また、カタカナが長く続く単語に対する、可読性の向上も併せて実施

fixes #260 metadata/managing-post-metadata/index.md textlint再実施

---

plugin-basics/index.md

Fixes #262
　44行目：Unix => UNIX
　154行目：削除することもできます => 削除できます

fixes #262 plugin-basics/index.md textlint再実施

---

wordpress-org/using-the-forums/index.md

fixes #218 wordpress-org/using-the-forums/index.md 和訳しました。

---

rest-api/requests/index.md

Fixes #274
　14行目：様々 => さまざま
　24行目：様々 => さまざま
　34行目：様々 => さまざま
　34行目：様々 => さまざま
　43行目：様々 => さまざま
　53行目：殆ど => ほとんど
　53行目：様々 => さまざま
　83行目：訳 => わけ
　93行目：殆ど => ほとんど
　160行目：殆ど => ほとんど
　185行目：様々 => さまざま
　190行目：訳 => わけ
　390行目：揃っ => そろっ
　390行目：例え => たとえ
　405行目：素晴らし => すばらし
　405行目：面白 => おもしろ

fixes #274 rest-api/requests/index.md textlint再実施

---

rest-api/rest-api-overview/index.md

Fixes #278
　29行目：が故に => がゆえに
　52行目：コントローラー => コントローラ
　57行目：上 => うえ
　102行目：コントローラー => コントローラ
　107行目：コントローラー => コントローラ
　107行目：コントローラー => コントローラ

fixes #278 rest-api/rest-api-overview/index.md textlint再実施

---

wordpress-org/transferring-your-plugin-to-a-new-owner/index.md

Fixes #312
　56行目：為 => ため
　75行目：殆ど => ほとんど
　75行目：繋が => つなが

fixes #312 wordpress-org/transferring-your-plugin-to-a-new-owner/index.md textlint再実施

---

wordpress-org/special-user-roles-capabilities/index.md

Fixes #310
　9行目：為 => ため
　49行目：為 => ため
　14行目：持てる => 持ている　←「prh」ルールですが、「持っている」ではなく、こういう言い回しがあるのですか？typoなら、ルール自体の訂正が必要では？

fixes #310 wordpress-org/special-user-roles-capabilities/index.md textlint再実施

---

wordpress-org/previews-and-blueprints/index.md

fixes #308 wordpress-org/previews-and-blueprints/index.md textlint再実施

---

wordpress-org/preventing-wordpress-from-updating-your-external-plugin/index.md

Fixes #306
　29行目：の様な => のような
　29行目：例え => たとえ
　34行目：為 => ため
　49行目：例え => たとえ

fixes #306 wordpress-org/preventing-wordpress-from-updating-your-external-plugin/index.md textlint再実施

---

wordpress-org/plugin-security/reporting-plugin-security-issues/index.md

Fixes #304
　14行目：殆ど => ほとんど
　40行目：殆ど => ほとんど
　45行目：既に => すでに

fixes #304 wordpress-org/plugin-security/reporting-plugin-security-issues/index.md textlint再実施

---

wordpress-org/detailed-plugin-guidelines/index.md

fixes #300 wordpress-org/detailed-plugin-guidelines/index.md textlint再実施

---

wordpress-org/add-your-plugin-to-the-block-directory/index.md

Fixes #298
　36行目：為 => ため
　36行目：遥か => はるか
　75行目：この様な => このような

fixes #298 wordpress-org/add-your-plugin-to-the-block-directory/index.md textlint再実施

---

taxonomies/index.md

Fixes #290
　35行目：この章 => 本章
　41行目：4 以 => 4以
　41行目：5 で => 5で
他に、ダブルクォーテーションで顔まれた単語について、「」で囲む様に変更しました。

fixes #290 taxonomies/index.md textlint再実施

---

rest-api/responses-2/index.md

Fixes #276
　14行目：全て => すべて
　53行目：この様に => このように
　82行目：様々 => さまざま
　97行目：様々 => さまざま
　102行目：例え => たとえ
　248行目：辿れ => たどれ
　248行目：於いて => おいて
　248行目：辿れ => たどれ
　248行目：素晴らし => すばらし
　253行目：て欲し => てほし

fixes #276 rest-api/responses-2/index.md textlint再実施

---

wordpress-org/plugin-developer-faq/index.md

Fixes #314
　136行目：仕組み => しくみ
　206行目：移譲 => 委譲
　524行目：構わ => かまわ
　579行目：構い => かまい
　614行目：お勧め => おすすめ
　624行目：構い => かまい
　719行目：とは言え、 => とはいえ、
　864行目：確かに => たしかに
　944行目：付箋 => ふせん
　1124行目：2 ま => 2ま
　1229行目：稀 => まれ
　1388行目：台無し => 台なし

fixes #314 wordpress-org/plugin-developer-faq/index.md textlint再実施

---

wordpress-org/compliance-disclaimers/index.md

※24行目：「どの様なコンプライアンス」「提供している訳ではなく」に対して、それぞれ「どのよう」「わけ」に修正せよ、と。
※29行目：「明確に伝える為に」に対して、「ため」に修正せよ、と。
※44、59、84行目：「例えば」に対して、「たとえば」に修正せよ、と。
※104行目：「更なる」に対して、「さらなる」に修正せよ、と。
※114行目：「この様なこと」「良き世話人である為には」に対して、それぞれ「このような」「ため」に修正せよ、と。
※129行目：「既に」「与える訳ではない」「勿論」に対して、それぞれ「すでに」「わけではない」「もちろん」に修正せよ、と。
そこからブランチ

fixes #216 wordpress-org/compliance-disclaimers/index.md 和訳しました。

---

wordpress-org/how-your-readme-txt-works/index.md

Fixes #316
textlint実施の結果です：
　14行目：エントリ => エントリー　←警告が永久ループ（対処したら、今度は元に戻せ、とエラーが出る）
　187行目：]( => ] (　←textlintのprhルールは、markdown記法での「リンク」に対応してない？？
そこからブランチ

fixes #316 wordpress-org/how-your-readme-txt-works/index.md 和訳しました。

---

wordpress-org/take-over-an-existing-plugin/index.md

Fixes #318
textlintチェック結果：エラーなし
そこからブランチ

fixes #318 wordpress-org/take-over-an-existing-plugin/index.md 和訳しました。

---

wordpress-org/block-specific-plugin-guidelines/index.md

Fixes #320
textlintチェック結果：エラーなし
そこからブランチ

fixes #320 wordpress-org/block-specific-plugin-guidelines/index.md 和訳しました。

---

wordpress-org/block-specific-plugin-guidelines/index.md

Fixes #348
原文 17 行目：https://wordpress.org/plugins/browse/block/
和訳 19 行目：https://ja.wordpress.org/plugins/browse/block/

fixes #348 wordpress-org/block-specific-plugin-guidelines/index.md リンク先を日本語版プラグイン・ディレクトリに変更

---

internationalization/localization/index.md

Fixes #344
原文 163 行目：https://wordpress.org/plugins/glotpress/
和訳 168 行目：https://ja.wordpress.org/plugins/glotpress/

fixes #344 internationalization/localization/index.md リンク先を日本語版プラグイン・ディレクトリに変更

---

developer-tools/helper-plugins/index.md

Fixes #342
原文 21 行目：https://wordpress.org/plugins/plugin-check/
和訳 24 行目：https://ja.wordpress.org/plugins/plugin-check/
原文 34 行目：https://wordpress.org/plugins/query-monitor/
和訳 36 行目：https://ja.wordpress.org/plugins/query-monitor/

fixes #342 developer-tools/helper-plugins/index.md リンク先を日本語版プラグイン・ディレクトリに変更

---

developer-tools/debug-bar-and-add-ons/index.md

Fixes #340
原文 29 行目：https://wordpress.org/plugins/debug-bar/
和訳 31 行目：https://ja.wordpress.org/plugins/debug-bar/
原文 41 行目：https://wordpress.org/plugins/debug-bar-console/
和訳 43 行目：https://ja.wordpress.org/plugins/debug-bar-console/
原文 69 行目：https://wordpress.org/plugins/debug-bar-shortcodes/
和訳 71 行目：https://ja.wordpress.org/plugins/debug-bar-shortcodes/
原文 90 行目：https://wordpress.org/plugins/debug-bar-constants/
和訳 92 行目：https://ja.wordpress.org/plugins/debug-bar-constants/
原文 102 行目：https://wordpress.org/plugins/debug-bar-post-types/
和訳 104 行目：https://ja.wordpress.org/plugins/debug-bar-post-types/
原文 136 行目：https://wordpress.org/plugins/debug-bar-cron/
和訳 138 行目：https://ja.wordpress.org/plugins/debug-bar-cron/
原文 148 行目：https://wordpress.org/plugins/debug-bar-actions-and-filters-addon/ …

fixes #340 developer-tools/debug-bar-and-add-ons/index.md リンク先を日本語版プラグイン・ディレクトリに変更

---

wordpress-org/how-to-use-subversion/index.md

Fixes #350
原文 474 行目：https://wordpress.org/plugins/developers/#readme
和訳 476 行目：https://ja.wordpress.org/plugins/developers/#readme

fixes #350 wordpress-org/how-to-use-subversion/index.md リンク先を日本語版プラグイン・ディレクトリに変更

---

wordpress-org/how-your-readme-txt-works/index.md

Fixes #352
原文 12 行目：https://wordpress.org/plugins/readme.txt
和訳 14 行目：https://ja.wordpress.org/plugins/readme.txt
原文 17 行目：https://wordpress.org/plugins/developers/readme-validator/
和訳 19 行目：https://ja.wordpress.org/plugins/developers/readme-validator/

fixes #352 wordpress-org/how-your-readme-txt-works/index.md リンク先を日本語版プラグイン・ディレクトリに変更

---

plugin-basics/index.md

Fixes #336
原文 199 行目：[Hello Dolly](https://wordpress.org/plugins/hello-dolly/ "Hello Dolly")
和訳 202 行目：[Hello Dolly](https://ja.wordpress.org/plugins/hello-dolly/ "Hello Dolly")
リンク先を日本語版に変更。

fixes #336 plugin-basics/index.md 和訳の見直し

---

intro/index.md

Fixes #326
リンクテキストの「タイトル」と、リンク先を日本語版に変更。

fixes #326 intro/index.md 和訳の見直し

---

wordpress-org/planning-submitting-and-maintaining-plugins/index.md

Fixes #354
原文 7 行目：https://wordpress.org/plugins/hello-dolly/
和訳 9 行目：https://ja.wordpress.org/plugins/hello-dolly/
原文 42 行目：https://wordpress.org/plugins/developers/#readme
和訳 44 行目：https://ja.wordpress.org/plugins/developers/#readme
原文 68 行目：https://wordpress.org/plugins/developers/add/
和訳 72 行目：https://ja.wordpress.org/plugins/developers/add/
原文 80 行目：https://wordpress.org/plugins/developers/#readme
原文 80 行目：https://wordpress.org/plugins/
和訳 82 行目：https://ja.wordpress.org/plugins/developers/#readme
和訳 82 行目：https://ja.wordpress.org/plugins/
原文 95 行目：https://wordpress.org/plugins/developers/add/
和訳 97 行目：https://ja.wordpress.org/plugins/developers/add/

fixes #354 wordpress-org/planning-submitting-and-maintaining-plugins/index.md リンク先を日本語版プラグイン・ディレクトリに変更

---

wordpress-org/plugin-developer-faq/index.md

Fixes #356
原文 57 行目：https://wordpress.org/plugins/developers/add/
和訳 59 行目：https://ja.wordpress.org/plugins/developers/add/
原文 442 行目：https://wordpress.org/plugins/developers/#readme
和訳 444 行目：https://ja.wordpress.org/plugins/developers/#readme
原文 462 行目：https://wordpress.org/plugins/developers/#readme
和訳 464 行目：https://ja.wordpress.org/plugins/developers/#readme
原文 547 行目：https://wordpress.org/plugins/developers/#readme
和訳 549 行目：https://ja.wordpress.org/plugins/developers/#readme
原文 562 行目：https://wordpress.org/plugins/developers/#readme
和訳 564 行目：https://ja.wordpress.org/plugins/developers/#readme
原文 987 行目：https://wordpress.org/plugins/_MY_PLUGIN_/advanced/
和訳 989 行目：https://ja.wordpress.org/plugins/_MY_PLUGIN_/advanced/
原文 1291 行目：https://wordpress.org/plugins/_YOUR_PLUGIN_/advanced …

fixes #356 wordpress-org/plugin-developer-faq/index.md リンク先を日本語版プラグイン・ディレクトリに変更

---

wordpress-org/transferring-your-plugin-to-a-new-owner/index.md

Fixes #360
原文 27 行目：https://wordpress.org/plugins/YOURPLUGIN/advanced
和訳 30 行目：https://ja.wordpress.org/plugins/YOURPLUGIN/advanced

fixes #360 wordpress-org/transferring-your-plugin-to-a-new-owner/index.md リンク先を日本語版プラグイン・ディレクトリに変更

---

wordpress-org/add-your-plugin-to-the-block-directory/index.md

Fixes #346
原文 39 行目：https://wordpress.org/plugins/browse/block/
原文 39 行目：https://wordpress.org/plugins/developers/block-plugin-validator/
和訳 41 行目：https://ja.wordpress.org/plugins/browse/block/
和訳 41 行目：https://ja.wordpress.org/plugins/developers/block-plugin-validator/

fixes #346 wordpress-org/add-your-plugin-to-the-block-directory/index.md リンク先を日本語版プラグイン・ディレクトリに変更

---

javascript/jquery/index.md

また、textlint エラー（セレクター => セレクタ）への対応も実施

fixes #367 javascript/jquery/index.md リンクのタイトルの見直し（和訳）

---

README.md

リポジトリの設定方法内、コマンドで移動する先のディレクトリ名が誤っていたため修正。

README: リポジトリの管理方法のコマンドを修正

---

wordpress-org/transferring-your-plugin-to-a-new-owner/index.md

wordpress-org/transferring-your-plugin-to-a-new-owner/index.md 和訳の追加

---

wordpress-org/plugin-developer-faq/index.md

GitHub 上でREADMEファイルを見たときに、正しくリンクされないため。

アンカーリンクをフルURLに置き換える

---

shortcodes/index.md
shortcodes/tinymce-enhanced-shortcodes/index.md

ショートコードを文字列そのものとして表示させるために、ダブルカッコによってエスケープします。

ショートコードのエスケープ
