administration-menus/sub-menus/index.md
administration-menus/top-level-menus/index.md
assets/index.md
internationalization/how-to-internationalize-your-plugin/index.md
internationalization/index.md
internationalization/localization/index.md
internationalization/security/index.md
javascript/heartbeat-api/index.md
javascript/jquery/index.md
javascript/summary/index.md

下記 issue に相当する和訳です。
#5 administration-menus /sub-menus/ index.md 和訳します。
#6 administration-menus/top-level-menus /index.md を和訳します。

issue #5, #6, #8, #9, #10, #11, #12, #13, #14, #15 の和訳

---

privacy/privacy-related-options-hooks-and-capabilities/index.md

privacy/privacy-related-options-hooks-and-capabilities/index.md: 原文見出しのリストア

---

administration-menus/top-level-menus/index.md

　35行目：例え => たとえ
　40行目：行ない => 行い
　45行目：お勧め => おすすめ
　71行目：行なう => 行う
　154行目：例え => たとえ
　188行目：お勧め => おすすめ
　198行目：することができ => でき
　249行目：することができ => でき

fixes #222 administration-menus/top-level-menus/index.md textlint再実施

---

developer-tools/index.md

fixes #234 developer-tools/index.md textlint再実施

---

internationalization/index.md

　14行目：に 1 => に1
　14行目：8 文 => 8文
　24行目：提供することはできない => 提供できない
　24行目：することができ => でき

fixes #240 internationalization/index.md textlint再実施

---

javascript/summary/index.md

　9行目：2 つ => 2つ
　19行目：の 1 => の1

fixes #256 javascript/summary/index.md textlint再実施

---

metadata/index.md

fixes #258 metadata/index.md textlint再実施

---

plugin-basics/activation-deactivation-hooks/index.md

fixes #264 plugin-basics/activation-deactivation-hooks/index.md textlint再実施

---

post-types/index.md

fixes #266 post-types/index.md textlint再実施

---

privacy/index.md

fixes #268 privacy/index.md textlint再実施

---

privacy/suggesting-text-for-the-site-privacy-policy/index.md

fixes #270 privacy/suggesting-text-for-the-site-privacy-policy/index.md textlint再実施

---

rest-api/schema/index.md

Fixes #282
　14行目：の様に => のように
　14行目：殆ど => ほとんど
　24行目：方 => 人
　47行目：の様な => のような
　184行目：の様に => のように
　184行目：の様に => のように

fixes #282 rest-api/schema/index.md textlint再実施

---

taxonomies/working-with-custom-taxonomies/index.md

fixes #294 taxonomies/working-with-custom-taxonomies/index.md textlint再実施

---

taxonomies/split-terms-wp-4-2/index.md

fixes #292 taxonomies/split-terms-wp-4-2/index.md textlint再実施

---

shortcodes/index.md

fixes #288 shortcodes/index.md textlint再実施

---

settings/settings-api/index.md

Fixes #286
　19行目：登録と検証を行う => 登録したり検証する

fixes #286 settings/settings-api/index.md textlint再実施

---

security/checking-user-capabilities/index.md

fixes #284 security/checking-user-capabilities/index.md textlint再実施

---

users/roles-and-capabilities/index.md

Fixes #362
原文 52 行目：Users roles
和訳 54 行目：ユーザーの権限グループ

fixes #362 users/roles-and-capabilities/index.md 画像リンクの代替テキストなどの見直し

---

hooks/advanced-topics/index.md

hooks/advanced-topics/index.md 原文の変更に追随

---

wordpress-org/previews-and-blueprints/index.md

Update: wordpress-org/previews-and-blueprints/index.md

---

wordpress-org/common-issues/index.md

wordpress-org/common-issues/index.md 原文の変更に追随

---

wordpress-org/add-your-plugin-to-the-block-directory/index.md

wordpress-org/add-your-plugin-to-the-block-directory/index.md 和訳の追加

---

wordpress-org/special-user-roles-capabilities/index.md

wordpress-org/special-user-roles-capabilities/index.md 和訳の追加

---

javascript/ajax/index.md

javascript/ajax/index.md 和訳の見直し（原文の記述変更に追随）
